Add migration for infoblox plugins
theforeman/foreman-installer pull request #201
Opened 2016-09-19 15:31 UTC by iNecas

2016-09-19 15:35 UTC, ekohl approved these changes

2016-09-20 07:18 UTC, domcleal requested changes
I think these should also be listed in the default config files, config/foreman.yaml and foreman-answers.yaml.

2016-09-20 07:31 UTC, iNecas commented
Updated

2016-09-20 07:34 UTC, domcleal approved these changes

2016-09-20 10:55 UTC, merged

2016-09-20 10:55 UTC, domcleal commented
Merged, thanks @iNecas.