refs #16207 - allow users to provide custom hiera configuration
theforeman/foreman-installer pull request #204
Opened 2016-10-20 17:40 UTC by stbenjam

A lot of enterprise-y users have security requirements they're required to use on their servers - things like turning server signature, trace, etc off in Apache.  We've had other cases in Katello where users wanted to tweak qpid or pulp settings to allow for more threads/workers/etc, for example.
Not everything should be exposed at the top-level of the installer, exposing Apache configuration would be an absurd number of parameters.

This adds support for a user-supplied `custom.yaml` they'd drop into /usr/share/foreman-installer/config/foreman.hiera.

So for example, someone following a security guide that requires some things, they could do:

```yaml
---
apache::server_tokens: Prod
apache::server_signature: Off
apache::trace_enable: Off
```

This is preserved across installer runs.

2016-10-20 20:45 UTC, ekohl commented
Like I said on IRC: I like this solution. I think the custom.yaml should live in ```/etc/foreman-installer``` somewhere. Some sample files could be useful but that could also be solved in the documentation rather than ```/usr/share/doc```.

2016-10-21 01:38 UTC, stbenjam commented
@ekohl Thanks for the feedback, I added an example YAML.  A symlink would be handled in the packaging, I'll open PR's if this is accepted.

2016-10-21 07:12 UTC, domcleal requested changes

2016-10-21 07:12 UTC, domcleal commented on config/foreman-hiera.conf
> +  - custom
Shouldn't custom be at the top of the hierarchy, most important?

2016-10-21 07:14 UTC, domcleal commented
> A symlink to custom.yaml in /etc/foreman-installer would be handled in the packaging

I think it should be in the build script (Rakefile) here, not in packaging.

2016-10-28 20:08 UTC, mmoll approved these changes

2016-10-30 12:15 UTC, ekohl commented on config/foreman-hiera.conf
> +  - custom
This question wasn't answered. Should it?

2016-10-30 13:06 UTC, mmoll commented on config/foreman-hiera.conf
> +  - custom
It was moved to the top in the current diff

2016-10-30 21:15 UTC, ekohl approved these changes
You're right. @domcleal does this address your comments?

2016-10-30 21:26 UTC, ekohl commented
Once this is merged, should we modify https://github.com/theforeman/kafo/blob/68eb8b2c9765f402a4747ffcd61b59aebd751c2c/modules/kafo_configure/manifests/init.pp to accept arbitrary classes and defines to include as an extension point or would it make more sense to include some other wrapper module? I like the idea of a profile module (puppet-foreman_tuning?) that has some presets. For example to apply some tuning to apache and postgresql.

2016-10-31 07:54 UTC, domcleal requested changes

2016-10-31 07:54 UTC, domcleal commented on Rakefile
> +  ln_s "#{DATADIR}/foreman-installer/config/foreman.hiera/custom.yaml", "#{SYSCONFDIR}/foreman-installer/custom-hiera.yaml"
I think this symlink's backwards, is the file meant to be stored in /etc but the symlink in /usr? It's currently in /usr but the symlink is in /etc.

2016-10-31 07:55 UTC, domcleal commented
> Once this is merged, should we modify https://github.com/theforeman/kafo/blob/68eb8b2c9765f402a4747ffcd61b59aebd751c2c/modules/kafo_configure/manifests/init.pp to accept arbitrary classes and defines

It already uses hiera_include which would let you add to `classes` from this data file.

2016-10-31 09:29 UTC, ekohl commented
> It already uses hiera_include which would let you add to classes from this data file.

Will that merge properly?

2016-10-31 09:31 UTC, domcleal commented
Yes, it merges results from all layers of the hierarchy.

2016-10-31 12:06 UTC, stbenjam commented on Rakefile
> +  ln_s "#{DATADIR}/foreman-installer/config/foreman.hiera/custom.yaml", "#{SYSCONFDIR}/foreman-installer/custom-hiera.yaml"
Well, it was *meant* exactly as its written now, it seemed more straightforward to leave the file where it was.

Updated to use your suggestion.

2016-10-31 12:19 UTC, stbenjam commented
Updated

2016-10-31 14:22 UTC, domcleal approved these changes

2016-10-31 14:24 UTC, merged

2016-10-31 14:24 UTC, domcleal commented
Merged, thanks @stbenjam.