Add spec to compare answers/config to migrations
theforeman/foreman-installer pull request #208
Opened 2016-11-04 17:20 UTC by stbenjam

This ensures answers/config are up-to-date, and also effectively
performs a test that the migrations themselves are valid.

2016-11-04 17:21 UTC, stbenjam commented
The `rake config:migrate` task that applies the migrations, so you don't have to do it manually, wipes out comments unfortunately.  This wasn't a problem in katello-installer, as we don't have any.

But the tests themselves are maybe useful to foreman-installer?

2016-11-08 08:26 UTC, domcleal requested changes

2016-11-08 08:26 UTC, domcleal commented on Rakefile
> +  task :migrate do
Isn't this the same as `bin/foreman-installer --migrations-only`?

(I'm hesitant to add code using Kafo internals if unnecessary)

2016-11-08 12:23 UTC, stbenjam commented on Rakefile
> +  task :migrate do
Yes, for foreman-installer it is.  Removed it.

2016-11-08 12:24 UTC, domcleal requested changes

2016-11-08 12:24 UTC, domcleal commented on Rakefile
> +require 'kafo'
Unnecessary now the task using it's been removed.

2016-11-17 20:21 UTC, mmoll approved these changes

2016-11-18 08:50 UTC, domcleal approved these changes

2016-11-18 08:50 UTC, merged

2016-11-18 08:50 UTC, domcleal commented
Thanks @stbenjam. Please remember to reply to PR comments so we know to re-review.

2016-11-18 13:14 UTC, stbenjam commented
Label changes trigger a notification, don't they?

2016-11-18 13:35 UTC, domcleal commented
No, they don't.

2016-11-18 13:52 UTC, stbenjam commented
I don't rely on github notifications, so I didn't realize labels don't trigger a notification. What's the point of labeling something "Needs re-review" if it doesn't trigger any notification and no one looks at the label?

I use bugwarrior/taskwarrior so I do indeed notice when PR's I'm involved in switch labels and require an action from me.