[WIP] Add upgrade-puppet hook
theforeman/foreman-installer pull request #219
Opened 2017-02-07 18:12 UTC by ekohl

Based on the upgrade-puppet hook in katello-installer.

2017-02-07 18:16 UTC, ekohl commented
So this can be considered a preview. The helper was copied verbatim from katello-installer. I'm not sure if we need/want all of it but this allows me to quickly show a PoC. Currently it's broken but I'm interested to get some initial feedback.

2017-02-08 14:03 UTC, ekohl commented
Verified to work on CentOS 7 now.

2017-04-01 15:36 UTC, mmoll commented on hooks/pre/31-upgrade-puppet.rb
> +  # TODO: OS dependent + override
what's the status here?

2017-04-01 21:08 UTC, mmoll commented
looking good visually, but I'm unsure if I really can test drive this properly for 1.15

2017-04-01 21:17 UTC, ekohl commented
Updated, now also tested with Debian Jessie and stripped some unused code.

Regarding inclusion in 1.15: what would give you sufficient confidence?

2017-04-01 21:27 UTC, mmoll commented
As it is a new feature that's not interferring with the default install, I'd even merge it when you say, you tested it sucessfully under the OSes we support. We can ask people in the RC announcements to test and fix things on the way, if needed....

2017-04-05 21:01 UTC, mmoll commented
@domcleal any opinion on this PR?

2017-04-06 07:07 UTC, domcleal requested changes

2017-04-06 07:07 UTC, domcleal commented on hooks/boot/31-upgrade-puppet.rb
> +  '--upgrade-puppet',
This should contain the target version number (4), so as to leave room for 5 and future versions.

2017-04-06 07:07 UTC, domcleal commented on hooks/boot/01-helpers.rb
> +class Kafo::Helpers
It shouldn't be extending Kafo's modules from here, it should use its own namespace.

2017-04-06 07:07 UTC, domcleal commented on hooks/boot/01-helpers.rb
> +    def module_enabled?(kafo, name)
Already provided in hooks: https://github.com/theforeman/kafo#hooks

2017-04-06 07:07 UTC, domcleal commented on hooks/boot/01-helpers.rb
> +      Kafo::KafoConfigure.logger.send(level, message)
Similarly, `logger` should be in the hook context

2017-04-06 07:07 UTC, domcleal commented on hooks/pre/31-upgrade-puppet.rb
> +        p.value = nil
Should use `.unset_value`.

2017-04-06 07:13 UTC, domcleal commented
> @domcleal any opinion on this PR?

I'm unsure if this is safe enough to use and ship with the assumptions it makes about the user's environment, so aside from the technical points above, I'm not inclined to review/merge it.

2017-04-06 11:48 UTC, ekohl commented on hooks/boot/01-helpers.rb
> +    def module_enabled?(kafo, name)
I tried that, but didn't work

2017-04-06 11:48 UTC, ekohl commented on hooks/pre/31-upgrade-puppet.rb
> +        p.value = nil
When I tried that it didn't work. It would revert back to the value that was set before.

2017-04-08 17:03 UTC, mmoll commented
I'll need more time dive into this, but IMHO the assumptions that are made are correct for almost any Puppet 3 RPM and DEB install?

2018-01-18 12:27 UTC, ekohl commented
Closing this since Puppet 3 -> 4 is no longer relevant. Will revisit this when merging katello-installer into foreman-installer.

2018-01-18 12:27 UTC, closed without merging