Add logic to check executable of facter command
theforeman/foreman-installer pull request #230
Opened 2017-04-20 02:47 UTC by NewpTone

In some situation, facter is not installed or not exist in the system executable command path,  then 'facter fqdn' will fail and exit, this patch try to catch this exception.

2017-04-20 07:24 UTC, domcleal requested changes

2017-04-20 07:24 UTC, domcleal commented on checks/hostname.rb
> +MISSING = %q(Command 'facter' does not exist in system excutable path
'executable' typo

2017-04-20 07:24 UTC, domcleal commented on checks/hostname.rb
> +Make sure above command is installed and executable in your system. )
"Make sure _the_ above command"

2017-04-20 19:31 UTC, mmoll approved these changes

2017-04-21 07:11 UTC, domcleal approved these changes

2017-04-21 07:11 UTC, merged

2017-04-21 07:11 UTC, domcleal commented
Merged, thanks @NewpTone.

(It's a good idea to reply to comments so we know it's updated.)