Refs #6945 - use autosign path for puppetca
theforeman/foreman-installer pull request #231
Opened 2017-05-30 13:06 UTC by mmoll

2017-05-30 13:07 UTC, mmoll commented
to be merged after theforeman/puppet-foreman_proxy#350

2017-06-03 13:37 UTC, ekohl requested changes

2017-06-03 13:37 UTC, ekohl commented on config/foreman.migrations/20170530141108_foreman_proxy_autosignfile.rb
> +  answers['foreman_proxy']['use_autosignfile'] = true
This shouldn't happen unconditionally I think, only if it's nil.

2017-06-03 13:37 UTC, ekohl commented on config/foreman.migrations/20170530141108_foreman_proxy_autosignfile.rb
> +    puppetdir = answers['foreman_proxy']['puppetdir']
Delete the answer as well?

2017-06-03 13:53 UTC, mmoll commented on config/foreman.migrations/20170530141108_foreman_proxy_autosignfile.rb
> +  answers['foreman_proxy']['use_autosignfile'] = true
changed.

2017-06-03 13:54 UTC, mmoll commented on config/foreman.migrations/20170530141108_foreman_proxy_autosignfile.rb
> +    puppetdir = answers['foreman_proxy']['puppetdir']
$puppetdir still used in `templates/puppet_proxy_legacy.yml.erb`

2017-06-03 14:12 UTC, ekohl approved these changes

2017-06-03 18:30 UTC, mmoll commented
added a slash before 'autosign.conf'

2017-06-07 19:33 UTC, merged

2017-06-07 19:33 UTC, domcleal commented
Thanks @mmoll.