Pin postgres and concat
theforeman/foreman-installer pull request #232
Opened 2017-06-26 17:53 UTC by ehelms

Should be unpinned once puppetlabs/puppetdb dependency on postgres
is updated.

2017-06-26 18:08 UTC, mmoll requested changes

2017-06-26 18:08 UTC, mmoll commented on Puppetfile
> +mod 'puppetlabs/postgresql',    '< 5.0.0'
`mod 'puppetlabs/postgresql',    '>= 4.8.0', '< 5.0.0'` would be more correct

2017-06-26 18:38 UTC, ehelms commented
@mmoll Good call -- updated

2017-06-26 18:54 UTC, mmoll approved these changes

2017-06-26 18:54 UTC, merged

2017-06-26 18:54 UTC, mmoll commented
merged, thanks @ehelms!

2017-06-28 10:00 UTC, ekohl commented
When https://github.com/puppetlabs/puppetlabs-puppetdb/pull/260 is merged and released I think we can remove the pinning again.