Refs #15905 - Add forward/reverse dns check
theforeman/foreman-installer pull request #255
Opened 2017-10-25 21:07 UTC by chris1984

2017-10-25 21:08 UTC, chris1984 commented
Adding check based on @ekohl suggestion from https://github.com/Katello/katello-installer/pull/522, proof it works in that PR

2017-10-26 08:40 UTC, ekohl requested changes
I should have verified this when approving the katello-installer PR. Other than that you can use closes #8301.

2017-10-26 08:40 UTC, ekohl commented on checks/dns.rb
> +@reverse = `getent hosts #{@ip} | awk '{ print $2 }'`.chomp
This breaks when there are multiple IPs.

2017-10-26 19:45 UTC, chris1984 commented
@ekohl changed to yours, after testing today, can I get another review/merge please?

2017-10-30 09:29 UTC, ekohl approved these changes

2017-10-30 09:31 UTC, ekohl commented
Oh, if you could use ```Fixes #8301``` that'd make @theforeman-bot happy.

2017-10-30 14:26 UTC, chris1984 commented
@ekohl can i get a merge please, i fixed the commit message

2017-10-31 14:54 UTC, mmoll approved these changes

2017-10-31 14:55 UTC, mmoll commented
tested standalone with/etc/hosts entires, seems to work

2017-10-31 14:56 UTC, merged

2017-10-31 14:56 UTC, mmoll commented
merged, thanks @chris1984!