Fixes #23030 - Add SCL Mongo Hiera
theforeman/foreman-installer pull request #267
Opened 2018-03-27 14:48 UTC by chris1984

2018-03-27 21:15 UTC, ekohl requested changes
Currently it's not loaded because it's not in `config/foreman-hiera.conf`. I think this should live in ```config/foreman.hiera/RedHat.yaml``` because it's only applicable to Red Hat distros. If we supported Fedora then that needed an exception because it doesn't have SCLs. Even if we currently don't use mongo on any of these platforms, it's good to do it the right way.

2018-03-28 00:07 UTC, ehelms commented
I feel like this is it's own special change that should be reflected by it's own hiera file. And honestly, if possible, in katello-installer otherwise this provides an odd split of functionality. Could we add a new katello.yml file that the hiera config looks for in the hierarchy?

2018-03-29 14:29 UTC, ehelms commented
Does this have to be added to the hierarchy or will it just work cause it exists @ekohl ?

2018-03-29 14:44 UTC, ekohl requested changes
It needs to be added to the hierarchy.

2018-04-03 17:56 UTC, chris1984 commented
@ehelms updated the pr

2018-04-03 19:44 UTC, ehelms approved these changes
@ekohl final review on you

2018-04-09 17:53 UTC, ehelms commented on config/foreman.hiera/mongo-redhat-7.yaml
> +mongodb::server::storage_engine: 'wiredTiger'
@chris1984 This will force a change on upgrades won't it? Thus breaking upgrades? Remind me how were mitigating that.

2018-04-13 16:32 UTC, ekohl requested changes
The actual yaml file looks good, but I'd prefer to avoid setting variables on other distros - even if they are probably not used on those.

2018-04-13 16:32 UTC, ekohl commented on config/foreman-hiera.conf
> +  - mongo-redhat-7
The redhat should be `%{::osfamily}` and the `7` should be `%{::operatingsystemmajrelease}` so it's only loaded for EL7. You may need to rename the file to `mongo-RedHat-7.yaml`

2018-04-18 15:21 UTC, ehelms commented on config/foreman-hiera.conf
> +  - mongo-redhat-7
@chris1984 can you tackle this point?

2018-04-19 09:00 UTC, merged