Refs #22513 - add exposed params to hiera
theforeman/foreman-installer pull request #269
Opened 2018-04-04 15:51 UTC by chris1984

2018-04-04 16:01 UTC, ekohl requested changes

2018-04-04 16:01 UTC, ekohl commented on config/foreman.hiera/custom.yaml
> +# Here are some examples of how you tune the Postgres options if needed:
I'd add an empty line above this rather than below it.

2018-04-04 16:01 UTC, ekohl commented on config/foreman.hiera/custom.yaml
> +# postgresql::server::max_connections: 200
It should be a hash:
```yaml
postgresql::server::config_entries:
  max_connections: 200
  shared_buffers: 256MB
```

2018-04-04 16:04 UTC, chris1984 commented
@ekohl updated added an empty line above and below so it is not all jammed together and easy to read.

2018-04-04 16:05 UTC, ekohl approved these changes
This is pending a puppetlabs-postgresql release, but other than that I think this is correct.

2018-04-13 12:50 UTC, ehelms commented
@ekohl If possible, I'd like to get this in before we branch the installer, which would include possibly setting postgres to nightly (or at least the commit we are wanting to include). I think you said in the past that would be OK, but wondering when you are seeing the branch point of the installer is to see if we could go ahead and do this.

2018-04-23 15:00 UTC, ekohl requested changes
I think the commit message could be clearer. How about `Allow overriding postgresql server settings via hiera`

2018-04-23 15:00 UTC, ekohl commented on Puppetfile
> +mod 'puppetlabs/postgresql',    :git => 'https://github.com/puppetlabs/puppetlabs-postgresql'
Could you add a comment linking to https://tickets.puppetlabs.com/browse/MODULES-6963 so we know why it's there?

2018-04-23 15:07 UTC, chris1984 commented
@ekohl updated

2018-04-23 15:14 UTC, ekohl commented on config/foreman.hiera/custom.yaml
> +# Here are some examples of how you tune the Postgres options if needed:
I think the official spelling is PostgreSQL. @evgeni has been persistent in pointing this out so let's keep it correct.

2018-04-23 15:57 UTC, chris1984 commented
@ekohl updated

2018-04-23 16:04 UTC, ekohl approved these changes
@mmoll what do you think?

2018-04-23 16:10 UTC, mmoll requested changes
I'd rather fork that repo and have a defined state and not tap a foreign master branch

2018-04-23 18:25 UTC, ehelms commented
@mmoll Would setting Puppetfile to point at the commit in master we minimally want suffice for the time being?

2018-04-23 22:46 UTC, mmoll commented
@ehelms After having a look at the changes over there: Yes, that sounds sensible. :+1:

2018-04-23 23:57 UTC, chris1984 commented
@mmoll how does this look?

2018-04-24 00:23 UTC, mmoll commented on Puppetfile
> +mod 'puppetlabs/postgresql',    :git => 'https://github.com/puppetlabs/puppetlabs-postgresql' , :ref => 'Parameters `roles`, `config_entires`, and `pg_hba_rules` to `postgresql::server` for hiera'
please use the git commit id here

2018-04-24 12:18 UTC, ekohl requested changes

2018-04-24 12:18 UTC, ekohl commented on Puppetfile
> +mod 'puppetlabs/postgresql',    :git => 'https://github.com/puppetlabs/puppetlabs-postgresql' , :ref => 'Parameters `roles`, `config_entires`, and `pg_hba_rules` to `postgresql::server` for hiera'
I'd also prefer the current latest commit in master since there are docs changes as well as others.

2018-04-24 14:13 UTC, chris1984 commented
@ekohl @mmoll how does it look now?

2018-04-24 14:33 UTC, mmoll submitted a review, later dismissed

2018-04-24 14:36 UTC, ekohl commented on Puppetfile
> -mod 'puppetlabs/puppetdb'
Any reason you're removing puppetdb?

2018-04-24 14:43 UTC, mmoll approved these changes

2018-04-24 14:43 UTC, chris1984 commented
Updated

2018-04-24 14:51 UTC, ekohl approved these changes

2018-04-24 15:06 UTC, merged

2018-04-24 15:07 UTC, mmoll commented
merged, thanks @chris1984!