Refs #25170 - Add migration for new seed param naming.
theforeman/foreman-installer pull request #296
Opened 2018-10-15 17:00 UTC by chris1984

2018-10-16 14:50 UTC, ekohl requested changes
Note: you can test this easily by changing `config/foreman-answers.yaml` and add `admin_username: myadmin` under `foreman:`, run `bundle exec rake spec`. It should complain that there's a `initial_admin_username` answer present which wasn't in the answers. It's how I usually test migrations. I'm thinking about making that easier so you can provide some fixtures.

2018-10-16 14:50 UTC, ekohl commented on config/foreman.migrations/20181015123542_migrate_seed_params.rb
> +      mod["initial_#{var}"] = mod[var]
Looks like this needs a `unless mod[var].nil?`

2018-10-17 15:41 UTC, chris1984 commented
@ekohl this is what I get when I do that, does the output look correct for the manual test?

https://paste.fedoraproject.org/paste/fFVtzNcOKF4tdjUeWHl5iw

2018-12-14 20:37 UTC, ekohl requested changes
This now needs to be copied into the katello migration as well.

2019-01-08 01:51 UTC, ekohl approved these changes

2019-01-08 01:51 UTC, merged