Fixes #27462 - Capture the openssl error correctly
theforeman/foreman-installer pull request #376
Opened 2019-07-29 12:24 UTC by hao-yu

Older openssl version will still return 0 exit code and "OK" message
for some errors, such as the openssl in RHEL 7. This cause the
katello-certs-check script not capturing certificate error correctly.
This patch fixed the issue.

2019-07-29 17:26 UTC, ekohl commented
This file is getting very complex, but we have a basic test for this file. Could you add a test case that covers this? https://github.com/theforeman/foreman-installer/blob/develop/spec/katello_certs_check_spec.rb is hopefully self documenting but I'll gladly help if you could provide some reproducer.

2019-08-07 18:47 UTC, ekohl requested changes
Letting the bot pick up the review

2020-01-17 13:48 UTC, ekohl commented
@hao-yu have you looked at my comments? It'd be nice to have a proper reproducer for this.

2020-01-21 10:02 UTC, hao-yu commented
@ekohl Sorry, about the late reply. I will try to reproduce again and see if this issue is still valid in the latest Satellite.

2020-07-31 11:41 UTC, ehelms commented
Hi @hao-yu -- is this an issue you are planning to revisit?

2020-11-18 12:44 UTC, hao-yu commented
Sorry, for the delay. I will close this issue as I don't think I have time to write a test for it which might take me some time. Additionally I haven't seen anyone hitting this issue lately

2020-11-18 12:44 UTC, closed without merging