Refs #28067 - defaults for dynflow sidekiq redis
theforeman/foreman-installer pull request #400
Opened 2019-10-22 17:51 UTC by ezr-ondrej

2020-01-06 20:08 UTC, ekohl requested changes

2020-01-06 20:08 UTC, ekohl commented on config/foreman.hiera/family/RedHat.yaml
> +redis::params::default_install: false
I think we do want the default install. We count on that in the pulpcore module
```suggestion
```

2020-01-06 20:08 UTC, ekohl commented on config/foreman.hiera/family/RedHat.yaml
> +redis::params::manage_repo: false
This should be set on the redis class itself
```suggestion
redis::manage_repo: false
```

2020-01-16 13:04 UTC, ehelms commented
This PR and https://github.com/theforeman/foreman-installer/pull/434/files are attempting to do the same thing. However, I think based on comments #434 is more correct at this point.

2020-01-16 13:42 UTC, ezr-ondrej commented
Closing in favor of #434

2020-01-16 13:42 UTC, closed without merging