Drop Katello upgrade steps for Mongo and Qpid certs
theforeman/foreman-installer pull request #406
Opened 2019-11-19 18:40 UTC by ehelms

There have been 10 releases since the qpidd upgrade step was introduced and 8 since we upgraded Mongo. Therefore, I feel fairly confident we can drop these from our current upgrade steps.

@jsherrill @chris1984

2019-11-19 18:42 UTC, chris1984 approved these changes
Yeah most people should be off Mongo 2.x now, ACK for the Mongo side of things

2019-11-19 19:16 UTC, chris1984 commented
I wrote the qpid piece too, so I think that is good to go as well, looking at this again.

2019-11-19 22:31 UTC, ekohl requested changes
I'm inclined to also trim down `upgrade_step` to remove tracking of all steps since it now always calls it with `:run_always => true`. We can also do that in a later commit. If we need it in the future, I actually want to use the mechanisms the installer has built in rather than this custom solution.

2019-11-19 22:31 UTC, ekohl commented on katello/hooks/post/09-mongo_syspath.rb
> -      `yum install -y -q rh-mongodb34-syspaths`
I think we still need to ensure this is installed. IIRC that can be done by setting the `mongodb::globals::server_package_name` to that in `config/foreman.hiera/family/RedHat-7.yaml`

2019-11-20 14:17 UTC, ehelms commented
Right now, I am planning to add a step for Postgres upgrade but I thought cleaning up first would be nice.

2019-11-20 15:35 UTC, ekohl approved these changes
Let's have a look at how the postgres one turns out. However, I'd like to use the native mechanism (`store_custom_config` and `get_custom_config`). See https://github.com/theforeman/foreman-installer/blob/5676453ec3226dff221cc1589a7118042fcdb843/katello/hooks/pre_commit/09-version_locking.rb on how to do that.

Of course that's all for the next PR and I'm now happy with this cleanup :)

2019-11-20 15:35 UTC, merged

2019-11-20 15:44 UTC, ekohl commented
Of course just now I realize that this could have used a Redmine issue to track. Please do one for the postgres upgrade :)