Set PostgreSQL 10 defaults on EL 7 for all scenarios
theforeman/foreman-installer pull request #427
Opened 2019-12-10 20:13 UTC by ehelms

This effectively moves Foreman and Katello Devel scenarios to PostgreSQL 10 as well without having to write a bunch of work arounds.

2019-12-11 13:48 UTC, ekohl requested changes
we'll need upgrade hooks in vanilla Foreman as well to upgrade those users as well. I'd prefer to first make sure Katello can upgrade safely before we copy those.

2019-12-18 14:22 UTC, ehelms commented
This PR (https://github.com/theforeman/foreman-installer/pull/436) will add the ground work for adding this upgrade flag.

2019-12-18 14:54 UTC, ekohl commented
https://github.com/theforeman/puppet-foreman/pull/781 will also simplify the logic needed.

2020-01-06 18:11 UTC, ehelms commented
Blocked on -- https://github.com/theforeman/foreman-installer/pull/440

2020-01-08 15:59 UTC, ehelms commented
Will now require migrating the upgrade hook to main Foreman -- https://github.com/theforeman/foreman-installer/pull/443

2020-01-13 12:28 UTC, ekohl commented
Looks like https://github.com/theforeman/foreman-installer/pull/444 now includes this so should we close this?

2020-01-13 13:51 UTC, closed without merging