Add foreman proxy scenario
theforeman/foreman-installer pull request #435
Opened 2019-12-17 16:59 UTC by ehelms

Includes https://github.com/theforeman/foreman-installer/pull/262 with updates

2019-12-17 17:15 UTC, ekohl requested changes
My issue with this is that we will need to update **all** manuals. They say nothing about passing in a `--scenario` argument. I'd like to hear @tbrisker's opinion about this as well. On the other hand, 2.0 is a good moment for that.

2019-12-17 17:15 UTC, ekohl commented on config/foreman-proxy-answers.yaml
> +  custom_repo: true
This no longer exists and can be dropped.

2019-12-17 17:34 UTC, tbrisker commented
I'm fine with adding a scenario, tbh I'm a bit surprised that while the installer is able to install just a proxy (and has been for a long while if i'm not mistaken), [the manual](https://theforeman.org/manuals/nightly/index.html#4.3.1SmartProxyInstallation) tells users to manually install it from packages.

2019-12-17 17:38 UTC, ekohl commented
That's from the advanced section. [Installation Scenarios](https://theforeman.org/manuals/nightly/index.html#3.2.3InstallationScenarios) describes how to use the installer for it. It basically comes down to passing in `--no-enable-foreman --no-enable-foreman-cli` and you have the same result as this. The benefit for us as maintainers is that we don't need to duplicate all the migrations. We also don't force uses to make an explicit choice whether something is a proxy or a foreman server: there's just components you can enable/disable.

2019-12-18 13:27 UTC, ehelms commented
I'm not sure I follow clearly what the argument against this is. As I see it we have two deployments in Foreman:

 1) Foreman Server w/ builtin proxy
 2) External proxy

We should make this obvious and easy for users to install one or the other.

2019-12-18 15:02 UTC, ekohl commented
> I'm not sure I follow clearly what the argument against this is

It is additional work for us and by merging this now we break a lot of documentation. First of all, this needs a Redmine issue so it's properly tracked in the release notes. Then we need to make sure our documentation is updated to reflect this before RC1. As long as we can make that happen, I'm good with it.

After that we should also consider how we handle it in forklift. For Katello we also generate `-proxy` boxes. Should we do the same for vanilla and further explode the number of boxes we have?

2019-12-18 16:23 UTC, ehelms commented
Ahh yea, I am good with making documentation updates. We technically are not breaking anything by including this. We are adding functionality that we can switch our documentation to as the preferred method for installation of a stand alone proxy but it does not invalidate the current method.

2019-12-20 19:10 UTC, ekohl commented
Well, before this change this worked:
```
yum -y install foreman-installer
foreman-installer
```

After it needs to be:
```
yum -y install foreman-installer
foreman-installer --scenario foreman
```

That means documentation changes.

2020-03-18 16:25 UTC, closed without merging