Refs #28697 - Use systemctl instead of foreman-maintain
theforeman/foreman-installer pull request #461
Opened 2020-02-05 10:17 UTC by ekohl

The benefit of this is that systemctl is quiet where foreman-maintain is very noisy. It also avoids the overhead of Ruby just to start a service that's already known.

2020-02-05 12:30 UTC, ehelms requested changes
I disagree with this change for the following reasons:

 1) This upgrade only happens one time, so I'm not worried about verbosity or speed of stopping a service
 2) This provides confusing code as there is no consistency of what tooling is used to manage services
 3) If the problem is with the foreman-maintain verbosity or implementation, let's fix it there because foreman-maintain isn't going away

2020-02-19 12:51 UTC, ehelms commented
@ekohl thoughts here?

2020-03-05 18:08 UTC, ekohl commented
I still would like to push this. It gets rid of the following output in forklift:
```
Running Start Services
    ================================================================================
    Check if command is run as root user:                                 [32m[1m[OK][0m
    --------------------------------------------------------------------------------
    Start applicable services: Starting the following service(s):
    postgresql
                                                                                    |                                                                                 /                                                                                 /                                                                                 -                                                                                 \                                                                                 |                                                                                 /                                                                                 -                                                                                 \                                                                                 |                                                                                 / starting postgresql                                                                                / starting postgresql                                                                                - starting postgresql                                                                                \ starting postgresql                                                                                | starting postgresql                                                                                / starting postgresql                                                                                - starting postgresql                                                                                \ starting postgresql                                                                                | starting postgresql                                                                                / starting postgresql                                                                                - starting postgresql                                                                                \ starting postgresql                                                                                | All services started                                                [32m[1m[OK][0m
    --------------------------------------------------------------------------------
    foreman-maintain service start --only=postgresql finished successfully!
    Running Stop Services
```

> If the problem is with the foreman-maintain verbosity or implementation, let's fix it there because foreman-maintain isn't going away

Personally I think foreman-maintain hasn't really arrived yet. Since there's no Debian support, we can't generally rely on it anyway. I also see it as generally foreman-maintain calls foreman-installer so we shouldn't go the other way in the dependency graph. That's just asking for problems.

FYI: https://projects.theforeman.org/issues/25630

2020-03-06 00:12 UTC, ehelms commented
I think that is a more general question worth raising but I disagree with this change here. Two lines later foreman-maintain is used so this is not avoiding it just mudding the waters. I believe I have an action item to expand this conversation around foreman-maintain elevation and would like to approach that.

2020-04-28 01:40 UTC, ehelms commented
Given the abstract layer now for foreman_maintain, can we close this in favor of that abstraction layer for now?

2020-04-28 09:28 UTC, ekohl commented
Sure, but I still want to get rid of foreman-maintain in the installer if possible. After dropping the mongo migration that will be easier.

2020-04-28 09:28 UTC, closed without merging