Fixes #30136: Do not proxy isos or yum on foreman proxy content
theforeman/foreman-installer pull request #521
Opened 2020-06-16 16:04 UTC by ehelms

2020-06-16 17:09 UTC, wbclark requested changes
@ehelms This change in answers would only affect new installations, correct? Therefore for users that upgraded there should also be a migration to disable the proxying of isos and rpm content.

2020-06-16 17:52 UTC, ehelms commented
Yessir, you are right. Helps if you git add new files when creating a PR :)

2020-06-16 18:39 UTC, jlsherrill commented
@ehelms looks like some rubocop failures

2020-06-16 18:53 UTC, ehelms commented
Addressed rubocop @jlsherrill @wbclark

2020-06-16 19:09 UTC, jlsherrill commented
LGTM @wbclark ?

2020-06-16 19:21 UTC, wbclark commented on config/foreman-proxy-content.migrations/200616155948-disable-pulp-3-proxying.rb
> +   answers[FOREMAN_PROXY_CONTENT][PROXY_YUM].nil? &&
I used this pattern previously when I was confident that answers[FPC] should already be a hash, but that wasn't the case for answers in this scenario previously, opening the possibility of a NoMethodError:

```
irb(main):012:0> answers
=> {"FPC"=>true}
irb(main):013:0> if answers['FPC']
irb(main):014:1>   puts "hello"
irb(main):015:1> end
hello
=> nil
irb(main):016:0> if answers['FPC'] && answers['FPC']['PROXY'].nil?
irb(main):017:1>   puts "hello"
irb(main):018:1> end
Traceback (most recent call last):
        2: from lib/tasks/console.rake:5:in `block in <top (required)>'
        1: from (irb):16
NoMethodError (undefined method `[]' for true:TrueClass)
irb(main):019:0> 
```

2020-06-16 19:39 UTC, wbclark commented on config/foreman-proxy-content.migrations/200616155948-disable-pulp-3-proxying.rb
> +   answers[FOREMAN_PROXY_CONTENT][PROXY_YUM].nil? &&
Hmmm, my usage may have been incorrect as well. I'm investigating it a bit further.

2020-06-16 19:54 UTC, wbclark commented on config/foreman-proxy-content.migrations/200616155948-disable-pulp-3-proxying.rb
> +   answers[FOREMAN_PROXY_CONTENT][PROXY_ISOS].nil?
```suggestion
if answers[FOREMAN_PROXY_CONTENT] == true ||
   (answers[FOREMAN_PROXY_CONTENT].is_a?(Hash) &&
   answers[FOREMAN_PROXY_CONTENT][PROXY_YUM].nil? &&
   answers[FOREMAN_PROXY_CONTENT][PROXY_ISOS].nil?)
```
I think this works in all cases.

2020-06-16 20:25 UTC, wbclark approved these changes
LGTM. Thanks @ehelms !

2020-06-16 20:28 UTC, merged

2020-06-29 11:07 UTC, tbrisker commented
2.1 - 1adc0d7