Fixes #29798 - Move --lock-package-versions to hooks/
theforeman/foreman-installer pull request #536
Opened 2020-07-02 09:54 UTC by ekohl

The primary goal of this PR is to move the hook from Katello to a shared one. An accidental move in 6e1a07bc35bfe97927dfac6477a1faf53092c58f resulted on this being executed on Debian which showed some flaws. Additional improvements are made to make it robust.

This uses the package_lock_feature? helper to determine whether locking is available. It then uses the newly introduced app_option? to determine if the option is available. This means it doesn't have to execute package_lock_feature? within the pre_commit hook again which saves an exec() of an external process.

In case locking could not be performed, the preference is cleared to allow the user to proceed. This saves them from having to edit the scenario manually. Instructions are printed to restore functionality.

This replaces https://github.com/theforeman/foreman-installer/pull/511

2020-07-02 13:21 UTC, wbclark requested changes
I'll go ahead and implement the `app_option?` helper in Kafo, unless there is some particular reason you want to hold off on it for now.

2020-07-02 13:21 UTC, wbclark commented on hooks/pre_commit/09-version_locking.rb
> +  Locking of package versions was requested but foreman-maintain couldn't be used for locking.
```suggestion
  Locking of package versions was requested but foreman-maintain could not be used for locking.
```

If I'm reading it correctly, Rubocop is actually complaining about this?

2020-07-02 13:21 UTC, wbclark commented on hooks/boot/01-kafo-hook-extensions.rb
> +    self.kafo.config.app.key?(option.to_sym)
```suggestion
    kafo.config.app.key?(option.to_sym)
```

2020-07-02 13:21 UTC, wbclark commented on hooks/pre_commit/09-version_locking.rb
> +  If locking is desired, ensure foreman-maintain can be used and rerun with --lock-package-versions.
```suggestion
  If locking is desired, ensure foreman-maintain can be used and rerun the installer with --lock-package-versions.
```

2020-07-02 13:27 UTC, ekohl commented
> I'll go ahead and implement the `app_option?` helper in Kafo, unless there is some particular reason you want to hold off on it for now.

No, I think that would be good to have. This was just the quickest way and I actually considered doing the Kafo change directly.

2020-09-01 18:41 UTC, wbclark commented
Hey @ekohl , heads up that `app_option?` helper is available in Kafo with https://github.com/theforeman/kafo/commit/77dbd25ba2d4aa54576cb73c9ac19e5fd50c720b

2020-09-02 18:06 UTC, ekohl commented
Rebased. Also split the hook context to localize methods.

2020-09-03 22:05 UTC, wbclark commented on hooks/pre_commit/09-version_locking.rb
> +  Locking of package versions was requested but foreman-maintain couldn't be used for locking.
Re-ran tests and it seems not to be an issue now. Marking as resolved.

2020-09-03 22:14 UTC, wbclark approved these changes
LGTM. Thanks @ekohl

2020-09-04 00:23 UTC, merged