Release 2.2.0-rc4
theforeman/foreman-installer pull request #594
Opened 2020-10-14 19:40 UTC by ehelms

2020-10-14 19:40 UTC, ehelms commented
@tbrisker here ya go

2020-10-15 05:51 UTC, tbrisker requested changes
Thanks, but this is missing a foreman_proxy release, we need 15.2.0+the two ACL changes after it (but not the puppetrun removal)

2020-10-19 14:45 UTC, tbrisker commented on Puppetfile
> +mod 'theforeman/foreman_proxy',      '>= 15.2.0 < 15.3.0'
You'll need to also update this at the bottom of `Puppetfile.lock`

2020-10-19 15:21 UTC, tbrisker commented
Failures due to `spec/fixtures/katello-certs-check/foreman.example.com.crt` being expired, we should probably fix that

2020-10-19 15:51 UTC, merged