Fixes #31502 - Add salt-plugin to proxy-answers
theforeman/foreman-installer pull request #631
Opened 2020-12-14 13:50 UTC by m-bucher

In order to have the commandline-parameters available in foreman-installer's foreman-proxy scenario.

2021-04-22 20:41 UTC, ehelms commented
Needs a rebase

2021-08-02 13:01 UTC, ehelms commented
You'll need to add a migration so that on upgrade the plugin is available.

2021-08-25 12:00 UTC, ekohl commented
Ping @m-bucher

2021-08-25 12:43 UTC, m-bucher commented
Thanks for the friendly reminder @ekohl, @ehelms :sweat_smile:

2022-05-26 12:31 UTC, ehelms commented
@m-bucher Would you like to rebase this change to get in?

2022-07-06 15:10 UTC, ekohl requested changes
Please rebase. It'd also be good to regenerate the migration so the filename is more up to date (it is a date stamp)

2022-07-07 07:54 UTC, m-bucher commented
@ekohl @ehelms , rebased :grin:

2022-07-07 09:16 UTC, ekohl approved these changes

2022-07-07 09:16 UTC, merged

2022-07-07 09:16 UTC, ekohl commented
Apologies for the long wait.