Fixes #36809 - Do not clobber answers provided on the command line wi…
theforeman/foreman-installer pull request #891
Opened 2023-10-06 19:55 UTC by ehelms

…th --certs-regenerate

2023-10-06 19:56 UTC, ehelms commented on hooks/pre_exit/20-certs_regenerate.rb
> +  kafo.send(:store_params)
I agree this is a bit ugly, calling into a private method. My goal here is to patch the problem first with a fix that can be cherry picked cleanly backward.

2023-10-06 19:57 UTC, ehelms commented
This is intended to be a patch that fixes the issue, and I think what needs to follow is a real fix to the way we regenerate certificates which is now possible that we have gotten rid of the RPM part.

2023-10-12 13:17 UTC, ekohl commented
Some notes: it was introduced in e28a51998be06ab97ce4d56b5fa16f1d2024ee33 and we shouldn't store `--certs-regenerate` but it should be passed to Puppet.

I'm now debating options, but can't think of any right now. I'll get back to this.

2023-12-15 14:31 UTC, ehelms commented
[test foreman-installer]

2024-01-16 02:46 UTC, ehelms commented
@ekohl This is still a pretty ugly problem that it can cause, do you have any additional thoughts or review?

2024-07-18 13:27 UTC, ehelms commented
@ekohl Do you have any additional ideas or can we move forward with this change to prevent this issue as-is for users?

2024-07-30 12:54 UTC, ekohl commented
My issue with the current implementation is that `--noop` or `--dont-save-answers` isn't respected: it always saves the answers.

I'm looking at https://github.com/theforeman/kafo/blob/master/doc/kafo_run.png and I'm wondering if we should take a different approach:
* In `pre_commit` we ensure the value is `false` in the answers file
* Kafo saves the answers
* In `pre` we set the answer back to what it was supposed to be

I don't know what the best mechanism is to store data between hooks. Our `store_custom_config` is probably the best we have.

2024-07-30 15:41 UTC, ehelms commented
> My issue with the current implementation is that `--noop` or `--dont-save-answers` isn't respected: it always saves the answers.
> 
> I'm looking at https://github.com/theforeman/kafo/blob/master/doc/kafo_run.png and I'm wondering if we should take a different approach:
> 
> * In `pre_commit` we ensure the value is `false` in the answers file
> * Kafo saves the answers
> * In `pre` we set the answer back to what it was supposed to be

None of this worked. And you are correct -- the current implementation saves the answers and that is why it's not working entirely correctly. I tried a variety of ideas using the `pre` state and could not get things to land in the correct state.

The approach I have proposed here modifies this to only reset the single parameter back to false rather than resetting *all* the answers back.

Ideally we get rid of the `regenerate` parameter, I think that is a bigger change and my aim here is to fix the existing problem in a minimal way.

2024-07-30 16:43 UTC, ekohl requested changes
Let's at least respect the `--noop` and `--dont-save-answers` flags and avoid storing the answers then. Then I think this is OK to merge.

2024-07-30 16:43 UTC, ekohl commented on hooks/pre_exit/20-certs_regenerate.rb
>  if module_enabled?('certs') && param('certs', 'regenerate').value == true
```suggestion
if !app_value(:noop) && !app_value(:dont_save_answers) && module_enabled?('certs') && param('certs', 'regenerate').value == true
```

2024-07-30 19:44 UTC, ehelms commented
> Let's at least respect the `--noop` and `--dont-save-answers` flags and avoid storing the answers then. Then I think this is OK to merge.

Accepted your update

2024-08-05 19:35 UTC, ehelms commented
@ekohl Are you good with this updated form?

2024-10-28 13:53 UTC, ehelms commented
@ekohl I would still like to get this localized fix in to prevent this issue for users and deal with the larger re-factor design issues as a follow up.

2026-02-03 13:58 UTC, closed without merging