Add hammer foreman_rh_cloud package
theforeman/foreman-installer pull request #900
Opened 2023-11-23 12:31 UTC by ShimShtein

2023-11-23 14:52 UTC, ekohl requested changes
You also need to create a migration using `bin/create-migration` for upgrading users with `answers['foreman::cli::rh_cloud'] ||= false`. You can pass the content to stdin.

2023-11-27 11:42 UTC, ekohl commented
Like this indeed, but the tests are unhappy now. I'm starting to wonder if those still provide good value, but for now please just make them pass.

2023-11-27 13:58 UTC, ShimShtein commented
Done. Tests are happy now.

2023-11-28 15:44 UTC, ekohl approved these changes

2023-11-28 15:44 UTC, merged