Fixes #37261 Add gitlab ci configuration
theforeman/foreman-installer pull request #918
Opened 2024-03-14 11:00 UTC by dosas

2024-03-14 11:54 UTC, dosas commented
Build failing due to network issues:
```
/usr/share/ruby/net/protocol.rb:46:in `connect_nonblock': Unable to connect to https://forgeapi.puppet.com (for request /v3/releases/puppet-systemd-6.6.0): Connection reset by peer - SSL_connect (Faraday::ConnectionFailed)
```

2024-03-14 14:14 UTC, ekohl requested changes
You missed the ` - ` between the issue number and the description in the commit message.

2024-03-14 14:14 UTC, ekohl commented on .gitignore
> +.xml
Line ending please

2024-03-14 14:24 UTC, dosas commented
> You missed the `-` between the issue number and the description in the commit message.

The parser didn't mind ;)

2024-03-14 18:10 UTC, ekohl approved these changes
I think it's OK to include this. @evgeni / @ehelms is this also something we would use downstream? Could it conflict with anything?

2024-03-14 18:27 UTC, evgeni commented
> I think it's OK to include this. @evgeni / @ehelms is this also something we would use downstream? Could it conflict with anything?

I recall talking to someone at cfgmgmtcamp that having gitlab ci stuff would be fine and we could *ideally* re-use it downstream -- or rip it out there.

2024-03-14 18:42 UTC, ehelms commented
It could conflict, but I would expect that we can modify this or attempt to
find ways to co-exist since no one version of it should be the source of
truth given nothing verifies this directly in our repo.

On Thu, Mar 14, 2024, 11:27 AM Evgeni Golov ***@***.***>
wrote:

> I think it's OK to include this. @evgeni <https://github.com/evgeni> /
> @ehelms <https://github.com/ehelms> is this also something we would use
> downstream? Could it conflict with anything?
>
> I recall talking to someone at cfgmgmtcamp that having gitlab ci stuff
> would be fine and we could *ideally* re-use it downstream -- or rip it
> out there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman-installer/pull/918#issuecomment-1998075296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACHT44ZATKP5DIGNVGIPJDYYHT2XAVCNFSM6AAAAABEV3XWHCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJYGA3TKMRZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-19 10:30 UTC, dosas commented
How can we fix the stuck test?

2024-03-19 10:36 UTC, evgeni commented
[test foreman-installer]

2024-03-19 11:22 UTC, dosas commented
Should we merge or combine this with existing downstream configurations first?

2024-03-19 11:29 UTC, evgeni commented
I'm fine merging this as-is and improving from there.

2024-03-21 15:48 UTC, dosas commented
I would merge it, if I could ;)

2024-03-21 17:22 UTC, ekohl commented on .gitlab-ci.yml
> +    - bundle exec "${PREFIX}"/sbin/foreman-proxy-certs-generate --help | grep -q certs-update-server
I would like to somehow generalize these steps so we don't duplicate them between this and Jenkins. Perhaps not a limitation for this PR, but if you have any thoughts on a good way that would be appreciated.

2024-03-21 17:37 UTC, dosas commented on .gitlab-ci.yml
> +    - bundle exec "${PREFIX}"/sbin/foreman-proxy-certs-generate --help | grep -q certs-update-server
* shell script
* rake task (I am not really familiar with it but there is already a `bundle exec rake install`)
* Makefile

2024-03-25 08:48 UTC, dosas commented on .gitlab-ci.yml
> +    - bundle exec "${PREFIX}"/sbin/foreman-proxy-certs-generate --help | grep -q certs-update-server
@ekohl I added it to the rakefile

2024-03-26 08:57 UTC, dosas commented
[test foreman-installer]

2024-03-27 08:03 UTC, dosas commented
@evgeni Could you please trigger the installer-tests?

2024-03-27 08:05 UTC, evgeni commented
ok to test

2024-04-02 11:14 UTC, dosas commented
Is this good to merge?

2024-04-09 08:52 UTC, ekohl approved these changes

2024-04-09 08:52 UTC, merged